#cloud-config
ssh_genkeytypes: ecdsa
disable_root: true
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding
repo_update: true
repo_upgrade: all

packages:
- python-setuptools
- python3-pip
- collectd-core
- postgresql-client
- jq
- curl
- nfs-common
- htop
- awscli
- ccze
- atop
- net-tools
- gcc
- git
- liblz4-tool
- aria2

runcmd:
- |
    #!/bin/bash
    aws s3 sync s3://${conf_bucket} /home/ubuntu/
    chmod 755 /home/ubuntu/*.sh
    chown -R ubuntu /home/ubuntu/
    sudo -u ubuntu /home/ubuntu/install_cosmos_exporter.sh
    sudo -u ubuntu /home/ubuntu/install_node_exporter.sh
    # ./home/ubuntu/install_node.sh
